version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=mydb
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # nginx serves on port 80 internally

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
